### ISSUE TITLE
Bug: Tray icon not visible

### ISSUE THREAD

**Issue by shinohara-rin** [cocoa-xu/enlightened#1]
![Untitled](https://github.com/cocoa-xu/enlightened/assets/25588514/0c4a1b6a-0c84-4ea1-be6e-d031b030cd91)

Albeit functional, the tray icon is not visible in the v1.0.0 package.

**Comment by cocoa-xu** [comment]
Ooops, I was using system symbols that available from macOS 14.0. It's now fixed in v1.0.1/
